import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { Feather } from '@expo/vector-icons';
import * as ImagePicker from 'expo-image-picker';
import * as Location from 'expo-location';
import { Audio } from 'expo-av';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { getNeighborhoods, submitComplaint, type MediaAttachment, type Neighborhood } from '@/api';
import { BottomNav } from '@/components/BottomNav';
import { colors, radius } from '@/theme';

function mediaFromAsset(asset: ImagePicker.ImagePickerAsset, fallback: string): MediaAttachment {
  const extension = asset.fileName?.split('.').pop() || fallback.split('/').pop() || 'bin';
  return { uri: asset.uri, name: asset.fileName || `murojaat-${Date.now()}.${extension}`, type: asset.mimeType || fallback };
}

export default function ComplaintScreen() {
  const DRAFT_KEY = 'emurojaat_complaint_draft';
  const [step, setStep] = useState(1); const [description, setDescription] = useState(''); const [firstName, setFirstName] = useState(''); const [phone, setPhone] = useState('+998');
  const [neighborhoods, setNeighborhoods] = useState<Neighborhood[]>([]); const [neighborhoodId, setNeighborhoodId] = useState(''); const [query, setQuery] = useState('');
  const [images, setImages] = useState<MediaAttachment[]>([]); const [video, setVideo] = useState<MediaAttachment | null>(null); const [audio, setAudio] = useState<MediaAttachment | null>(null); const [location, setLocation] = useState<{ latitude: number; longitude: number } | null>(null); const [recording, setRecording] = useState<Audio.Recording | null>(null);
  const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const [neighborhoodLoading, setNeighborhoodLoading] = useState(true);
  const filtered = useMemo(() => neighborhoods.filter((item) => item.name.toLowerCase().includes(query.toLowerCase())).slice(0, 8), [neighborhoods, query]);
  useEffect(() => { getNeighborhoods().then(setNeighborhoods).catch(() => setError('Mahallalar yuklanmadi. Telefon va kompyuter bir Wi-Fi tarmog‘ida ekanini tekshiring.')).finally(() => setNeighborhoodLoading(false)); }, []);
  useEffect(() => { AsyncStorage.getItem(DRAFT_KEY).then((value) => { if (!value) return; try { const draft = JSON.parse(value); setDescription(draft.description || ''); setFirstName(draft.firstName || ''); setPhone(draft.phone || '+998'); setNeighborhoodId(draft.neighborhoodId || ''); setQuery(draft.query || ''); setStep(draft.step || 1); } catch { /* ignore corrupt draft */ } }); }, []);
  useEffect(() => { AsyncStorage.setItem(DRAFT_KEY, JSON.stringify({ description, firstName, phone, neighborhoodId, query, step })).catch(() => undefined); }, [description, firstName, phone, neighborhoodId, query, step]);

  async function pickImages() { const permission = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) return setError('Rasmlarga kirish uchun ruxsat bering.'); const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ImagePicker.MediaTypeOptions.Images, allowsMultipleSelection: true, selectionLimit: 5 - images.length, quality: 0.85 }); if (!result.canceled) setImages((current) => [...current, ...result.assets.slice(0, 5 - current.length).map((asset) => mediaFromAsset(asset, 'image/jpeg'))]); }
  async function pickVideo() { const permission = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) return setError('Videoga kirish uchun ruxsat bering.'); const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ImagePicker.MediaTypeOptions.Videos, videoMaxDuration: 120, quality: 0.7 }); if (!result.canceled) setVideo(mediaFromAsset(result.assets[0], 'video/mp4')); }
  async function toggleRecording() { setError(''); if (recording) { await recording.stopAndUnloadAsync(); const uri = recording.getURI(); setRecording(null); if (uri) setAudio({ uri, name: `ovoz-${Date.now()}.m4a`, type: 'audio/mp4' }); return; } const permission = await Audio.requestPermissionsAsync(); if (!permission.granted) return setError('Ovoz yozish uchun ruxsat bering.'); await Audio.setAudioModeAsync({ allowsRecordingIOS: true, playsInSilentModeIOS: true }); const created = await Audio.Recording.createAsync(Audio.RecordingOptionsPresets.HIGH_QUALITY); setRecording(created.recording); }
  async function getLocation() { const permission = await Location.requestForegroundPermissionsAsync(); if (!permission.granted) return setError('Manzilni aniqlash uchun geolokatsiyaga ruxsat bering.'); const current = await Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.Balanced }); setLocation({ latitude: current.coords.latitude, longitude: current.coords.longitude }); }
  const next = () => { setError(''); if (step === 1 && description.trim().length < 10) return setError('Muammoni kamida 10 ta belgi bilan yozing.'); if (step === 2 && neighborhoodLoading) return setError('Mahallalar yuklanmoqda, biroz kuting.'); if (step === 2 && !neighborhoodId) return setError('Mahallani tanlang.'); if (step < 3) setStep(step + 1); };
  const send = async () => { setError(''); if (!firstName.trim() || phone.replace(/\D/g, '').length !== 12) return setError('Ism va to‘liq telefon raqamini kiriting.'); setLoading(true); try { const result = await submitComplaint({ description, firstName, lastName: '', phone: phone.replace(/\s/g, ''), neighborhoodId, ...location, images, video, audio }); await AsyncStorage.removeItem(DRAFT_KEY); router.replace({ pathname: '/track', params: { ticket: result.ticket_number, sent: '1' } }); } catch (e) { setError(e instanceof Error ? e.message : 'Yuborishda xatolik yuz berdi.'); } finally { setLoading(false); } };

  return <SafeAreaView edges={['top', 'left', 'right']} style={styles.safe}><KeyboardAvoidingView style={styles.flex} behavior={Platform.OS === 'ios' ? 'padding' : 'height'}><View style={styles.header}><Pressable onPress={() => step > 1 ? setStep(step - 1) : router.back()}><Feather name="arrow-left" size={23} color={colors.ink} /></Pressable><View style={styles.headerCopy}><Text style={styles.eyebrow}>{step} / 3 bosqich</Text><Text style={styles.headerTitle}>Murojaat yuborish</Text></View><View style={styles.stepPill}><Text style={styles.stepText}>{step}/3</Text></View></View><View style={styles.progress}><View style={[styles.progressFill, { width: `${(step / 3) * 100}%` }]} /></View><ScrollView contentContainerStyle={styles.body} keyboardShouldPersistTaps="handled">
    {step === 1 && <><Text style={styles.title}>Muammoingizni yozing</Text><Text style={styles.sub}>Aniq vaziyatni yozing yoki dalil biriktiring.</Text><TextInput value={description} onChangeText={setDescription} style={[styles.input, styles.textarea]} multiline placeholder="Masalan: ko‘chamizdagi chiroqlar ishlamayapti..." placeholderTextColor={colors.muted} textAlignVertical="top" /><View style={styles.mediaRow}><Pressable style={styles.mediaButton} onPress={pickImages}><Feather name="image" size={18} color={colors.teal} /><Text style={styles.mediaText}>Foto {images.length ? `(${images.length}/5)` : ''}</Text></Pressable><Pressable style={styles.mediaButton} onPress={pickVideo}><Feather name="video" size={18} color={colors.teal} /><Text style={styles.mediaText}>{video ? 'Video tanlandi' : 'Video'}</Text></Pressable><Pressable style={[styles.mediaButton, recording && styles.recording]} onPress={toggleRecording}><Feather name={recording ? 'square' : 'mic'} size={18} color={recording ? colors.danger : colors.teal} /><Text style={styles.mediaText}>{recording ? 'To‘xtatish' : audio ? 'Ovoz tanlandi' : 'Ovoz'}</Text></Pressable></View></>}
    {step === 2 && <><Text style={styles.title}>Manzilni tanlang</Text><Text style={styles.sub}>Murojaat qaysi mahallaga tegishli?</Text><TextInput value={query} onChangeText={setQuery} style={styles.input} placeholder="Mahalla nomini qidiring" placeholderTextColor={colors.muted} />{neighborhoodLoading ? <ActivityIndicator color={colors.teal} style={styles.neighborhoodLoader} /> : filtered.map((item) => <Pressable key={item.id} style={[styles.option, item.id === neighborhoodId && styles.optionSelected]} onPress={() => { setNeighborhoodId(item.id); setQuery(item.name); }}><Feather name={item.id === neighborhoodId ? 'check-circle' : 'map-pin'} size={18} color={item.id === neighborhoodId ? colors.teal : colors.muted} /><Text style={styles.optionText}>{item.name}</Text></Pressable>)}<Pressable style={[styles.locationButton, location && styles.optionSelected]} onPress={getLocation}><Feather name="navigation" size={18} color={colors.teal} /><Text style={styles.mediaText}>{location ? 'Joylashuv biriktirildi' : 'Joriy joylashuvni qo‘shish'}</Text></Pressable></>}
    {step === 3 && <><Text style={styles.title}>Bog‘lanish ma’lumotlari</Text><Text style={styles.sub}>Javob kelganda siz bilan bog‘lanishimiz uchun.</Text><TextInput value={firstName} onChangeText={setFirstName} style={styles.input} placeholder="Ismingiz" placeholderTextColor={colors.muted} /><TextInput value={phone} onChangeText={setPhone} style={styles.input} keyboardType="phone-pad" placeholder="+998 90 123 45 67" placeholderTextColor={colors.muted} /></>}
    {error ? <Text style={styles.error}>{error}</Text> : null}</ScrollView><View style={styles.bottom}><Pressable style={styles.primary} onPress={step < 3 ? next : send} disabled={loading}>{loading ? <ActivityIndicator color={colors.white} /> : <><Text style={styles.primaryText}>{step < 3 ? 'Davom etish' : 'Murojaatni yuborish'}</Text><Feather name={step < 3 ? 'arrow-right' : 'send'} size={19} color={colors.white} /></>}</Pressable></View></KeyboardAvoidingView><BottomNav active="new" onChange={() => router.replace('/cabinet')} /></SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background, paddingHorizontal: 20 }, flex: { flex: 1 }, header: { flexDirection: 'row', alignItems: 'center', gap: 14, paddingTop: 8 }, headerCopy: { flex: 1 }, eyebrow: { color: colors.teal, fontSize: 11, fontWeight: '800', textTransform: 'uppercase' }, headerTitle: { color: colors.ink, fontSize: 19, fontWeight: '800', marginTop: 3 }, stepPill: { backgroundColor: colors.mint, borderRadius: radius.pill, paddingHorizontal: 11, paddingVertical: 8 }, stepText: { color: colors.tealDark, fontWeight: '800' }, progress: { height: 5, backgroundColor: colors.line, borderRadius: 3, marginTop: 23, overflow: 'hidden' }, progressFill: { height: '100%', backgroundColor: colors.teal, borderRadius: 3 }, body: { paddingTop: 35, paddingBottom: 15 }, title: { color: colors.ink, fontSize: 29, fontWeight: '800', letterSpacing: -0.5 }, sub: { color: colors.muted, fontSize: 15, lineHeight: 22, marginTop: 8, marginBottom: 22 }, input: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.line, borderRadius: radius.control, minHeight: 54, paddingHorizontal: 16, color: colors.ink, fontSize: 16, marginBottom: 11 }, textarea: { minHeight: 185, paddingTop: 16 }, mediaRow: { flexDirection: 'row', gap: 8, marginBottom: 12 }, mediaButton: { flex: 1, minHeight: 51, borderRadius: radius.control, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.line, alignItems: 'center', justifyContent: 'center', gap: 4 }, recording: { borderColor: colors.danger, backgroundColor: '#FFF0F1' }, mediaText: { color: colors.ink, fontSize: 11, fontWeight: '700', textAlign: 'center' }, neighborhoodLoader: { marginVertical: 20 }, option: { minHeight: 52, borderRadius: radius.control, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.white, flexDirection: 'row', alignItems: 'center', gap: 11, paddingHorizontal: 15, marginBottom: 9 }, optionSelected: { borderColor: colors.teal, backgroundColor: colors.mint }, optionText: { color: colors.ink, fontSize: 15, fontWeight: '600' }, locationButton: { minHeight: 52, borderRadius: radius.control, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.white, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 9, marginTop: 4 }, error: { color: colors.danger, fontSize: 13, lineHeight: 18, marginTop: 7 }, bottom: { paddingVertical: 14 }, primary: { minHeight: 57, borderRadius: radius.control, backgroundColor: colors.teal, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10 }, primaryText: { color: colors.white, fontSize: 16, fontWeight: '800' } });
