import { useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router, useLocalSearchParams } from 'expo-router';
import { Feather } from '@expo/vector-icons';
import { trackComplaint, type TrackResult } from '@/api';
import { colors, radius } from '@/theme';

export default function TrackScreen() {
  const params = useLocalSearchParams<{ ticket?: string; sent?: string }>(); const [ticket, setTicket] = useState(params.ticket || ''); const [result, setResult] = useState<TrackResult | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const search = async () => { setError(''); setResult(null); if (!ticket.trim()) return setError('Murojaat raqamini kiriting.'); setLoading(true); try { setResult(await trackComplaint(ticket.trim())); } catch (e) { setError(e instanceof Error ? e.message : 'Murojaat topilmadi.'); } finally { setLoading(false); } };
  return <SafeAreaView style={styles.safe}><View style={styles.header}><Pressable onPress={() => router.back()}><Feather name="arrow-left" size={23} color={colors.ink} /></Pressable><Text style={styles.headerTitle}>Murojaat holati</Text></View>{params.sent ? <View style={styles.success}><Feather name="check-circle" size={21} color={colors.success} /><Text style={styles.successText}>Murojaat qabul qilindi. Raqamni saqlang.</Text></View> : null}<View style={styles.body}><Text style={styles.title}>Raqam orqali tekshiring</Text><Text style={styles.sub}>Murojaat yuborilganda berilgan ticket raqamini kiriting.</Text><TextInput value={ticket} onChangeText={setTicket} style={styles.input} autoCapitalize="characters" placeholder="UY-2026-000001" placeholderTextColor={colors.muted} /><Pressable style={styles.primary} onPress={search} disabled={loading}>{loading ? <ActivityIndicator color={colors.white} /> : <><Text style={styles.primaryText}>Holatni ko‘rish</Text><Feather name="search" size={19} color={colors.white} /></>}</Pressable>{error ? <Text style={styles.error}>{error}</Text> : null}{result ? <View style={styles.card}><View style={styles.statusRow}><Text style={styles.cardLabel}>Joriy holat</Text><View style={styles.status}><View style={styles.statusDot} /><Text style={styles.statusText}>{result.status_simple}</Text></View></View><Text style={styles.ticket}>{result.ticket_number}</Text><Text style={styles.meta}>{result.category.name}{result.department ? `  •  ${result.department.name}` : ''}</Text>{result.reply_text ? <View style={styles.reply}><Text style={styles.replyLabel}>Javob</Text><Text style={styles.replyText}>{result.reply_text}</Text></View> : null}</View> : null}</View></SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background, paddingHorizontal: 20 }, header: { flexDirection: 'row', alignItems: 'center', gap: 15, paddingTop: 8 }, headerTitle: { color: colors.ink, fontSize: 19, fontWeight: '800' }, body: { paddingTop: 52 }, title: { color: colors.ink, fontSize: 29, fontWeight: '800' }, sub: { color: colors.muted, fontSize: 15, lineHeight: 22, marginTop: 8, marginBottom: 22 }, input: { minHeight: 57, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.line, borderRadius: radius.control, paddingHorizontal: 16, color: colors.ink, fontSize: 16, marginBottom: 12 }, primary: { minHeight: 57, borderRadius: radius.control, backgroundColor: colors.teal, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10 }, primaryText: { color: colors.white, fontSize: 16, fontWeight: '800' }, error: { color: colors.danger, fontSize: 13, marginTop: 12 }, success: { marginTop: 22, borderRadius: radius.control, backgroundColor: '#E8F7EE', padding: 14, flexDirection: 'row', alignItems: 'center', gap: 9 }, successText: { color: colors.success, fontSize: 13, fontWeight: '700', flex: 1 }, card: { marginTop: 26, backgroundColor: colors.white, borderRadius: radius.card, padding: 19, borderWidth: 1, borderColor: colors.line }, statusRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, cardLabel: { color: colors.muted, fontSize: 13 }, status: { flexDirection: 'row', alignItems: 'center', gap: 6 }, statusDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.teal }, statusText: { color: colors.tealDark, fontSize: 13, fontWeight: '800' }, ticket: { color: colors.ink, fontSize: 25, fontWeight: '800', marginTop: 18, letterSpacing: 0.5 }, meta: { color: colors.muted, fontSize: 13, marginTop: 7 }, reply: { borderTopWidth: 1, borderTopColor: colors.line, marginTop: 18, paddingTop: 15 }, replyLabel: { color: colors.teal, fontSize: 12, fontWeight: '800' }, replyText: { color: colors.ink, fontSize: 14, lineHeight: 21, marginTop: 6 } });
